version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_STORAGE_USE_HTTPS=False
  producer:
    build: ./producer
    container_name: microservice_producer
    restart: always
    environment:
      - PRODUCER_HOST=0.0.0.0
      - PRODUCER_PORT=8081
      - RabbitMQ=amqp://guest:guest@host.docker.internal:5672
      - MINIO=minio:9000
      - MINIO_ACCESS_KEY=minio-root-user
      - MINIO_PASSWORD=minio-root-password
    ports:
      - 8080:8081
    depends_on:
      - rabbitmq
      - minio
  consumer:
    build: ./consumer
    container_name: microservice_consumer
    restart: always
    environment:
      - RabbitMQ=amqp://guest:guest@host.docker.internal:5672
      - MINIO=minio:9000
      - MINIO_ACCESS_KEY=minio-root-user
      - MINIO_PASSWORD=minio-root-password
    depends_on:
      - rabbitmq
      - minio
